[package]
name = "hello-immortal-world"
version = "0.1.0"
authors = ["Justin Grant Î» <justin@tpfs.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fort = "0.3"
bastion = "0.4.*"
